# Generated by Django 5.1 on 2024-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.CharField(max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('manual', models.FloatField(blank=True, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['dateTime'],
            },
        ),
        migrations.CreateModel(
            name='RainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('hourly_rainfall', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='RainDataFromFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('hourly_rainfall', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='ReplicatedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReplicatedDateDMY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceLevelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=8, null=True)),
                ('stage', models.FloatField(blank=True, null=True)),
                ('stage_min', models.FloatField(blank=True, null=True)),
                ('stage_max', models.FloatField(blank=True, null=True)),
                ('status', models.FloatField(blank=True, null=True)),
                ('status_min', models.FloatField(blank=True, null=True)),
                ('status_max', models.FloatField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('battery_min', models.FloatField(blank=True, null=True)),
                ('battery_max', models.FloatField(blank=True, null=True)),
                ('dc_load_a', models.FloatField(blank=True, null=True)),
                ('dc_load_a_min', models.FloatField(blank=True, null=True)),
                ('dc_load_a_max', models.FloatField(blank=True, null=True)),
                ('dc_load', models.FloatField(blank=True, null=True)),
                ('dc_load_min', models.FloatField(blank=True, null=True)),
                ('dc_load_max', models.FloatField(blank=True, null=True)),
                ('solar_panel_a', models.FloatField(blank=True, null=True)),
                ('solar_panel_a_min', models.FloatField(blank=True, null=True)),
                ('solar_panel_a_max', models.FloatField(blank=True, null=True)),
                ('solar_panel', models.FloatField(blank=True, null=True)),
                ('solar_panel_min', models.FloatField(blank=True, null=True)),
                ('solar_panel_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='SurfaceLevelDataFromFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=8, null=True)),
                ('stage', models.FloatField(blank=True, null=True)),
                ('stage_min', models.FloatField(blank=True, null=True)),
                ('stage_max', models.FloatField(blank=True, null=True)),
                ('status', models.FloatField(blank=True, null=True)),
                ('status_min', models.FloatField(blank=True, null=True)),
                ('status_max', models.FloatField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('battery_min', models.FloatField(blank=True, null=True)),
                ('battery_max', models.FloatField(blank=True, null=True)),
                ('dc_load_a', models.FloatField(blank=True, null=True)),
                ('dc_load_a_min', models.FloatField(blank=True, null=True)),
                ('dc_load_a_max', models.FloatField(blank=True, null=True)),
                ('dc_load', models.FloatField(blank=True, null=True)),
                ('dc_load_min', models.FloatField(blank=True, null=True)),
                ('dc_load_max', models.FloatField(blank=True, null=True)),
                ('solar_panel_a', models.FloatField(blank=True, null=True)),
                ('solar_panel_a_min', models.FloatField(blank=True, null=True)),
                ('solar_panel_a_max', models.FloatField(blank=True, null=True)),
                ('solar_panel', models.FloatField(blank=True, null=True)),
                ('solar_panel_min', models.FloatField(blank=True, null=True)),
                ('solar_panel_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='TSSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.CharField(max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('STAGE', models.FloatField(blank=True, null=True)),
                ('sheet_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('stage', models.FloatField(blank=True, null=True)),
                ('stage_min', models.FloatField(blank=True, null=True)),
                ('stage_max', models.FloatField(blank=True, null=True)),
                ('status', models.FloatField(blank=True, null=True)),
                ('status_min', models.FloatField(blank=True, null=True)),
                ('status_max', models.FloatField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('battery_min', models.FloatField(blank=True, null=True)),
                ('battery_max', models.FloatField(blank=True, null=True)),
                ('dc_load_a', models.FloatField(blank=True, null=True)),
                ('dc_load_a_min', models.FloatField(blank=True, null=True)),
                ('dc_load_a_max', models.FloatField(blank=True, null=True)),
                ('dc_load', models.FloatField(blank=True, null=True)),
                ('dc_load_min', models.FloatField(blank=True, null=True)),
                ('dc_load_max', models.FloatField(blank=True, null=True)),
                ('solar_panel_a', models.FloatField(blank=True, null=True)),
                ('solar_panel_a_min', models.FloatField(blank=True, null=True)),
                ('solar_panel_a_max', models.FloatField(blank=True, null=True)),
                ('solar_panel', models.FloatField(blank=True, null=True)),
                ('solar_panel_min', models.FloatField(blank=True, null=True)),
                ('solar_panel_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='WaterLevelDataFromFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('stage', models.FloatField(blank=True, null=True)),
                ('stage_min', models.FloatField(blank=True, null=True)),
                ('stage_max', models.FloatField(blank=True, null=True)),
                ('status', models.FloatField(blank=True, null=True)),
                ('status_min', models.FloatField(blank=True, null=True)),
                ('status_max', models.FloatField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('battery_min', models.FloatField(blank=True, null=True)),
                ('battery_max', models.FloatField(blank=True, null=True)),
                ('dc_load_a', models.FloatField(blank=True, null=True)),
                ('dc_load_a_min', models.FloatField(blank=True, null=True)),
                ('dc_load_a_max', models.FloatField(blank=True, null=True)),
                ('dc_load', models.FloatField(blank=True, null=True)),
                ('dc_load_min', models.FloatField(blank=True, null=True)),
                ('dc_load_max', models.FloatField(blank=True, null=True)),
                ('solar_panel_a', models.FloatField(blank=True, null=True)),
                ('solar_panel_a_min', models.FloatField(blank=True, null=True)),
                ('solar_panel_a_max', models.FloatField(blank=True, null=True)),
                ('solar_panel', models.FloatField(blank=True, null=True)),
                ('solar_panel_min', models.FloatField(blank=True, null=True)),
                ('solar_panel_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
