# Generated by Django 5.1 on 2024-10-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpikeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
