# Generated by Django 5.1 on 2024-12-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0002_spikedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFilling',
        ),
        migrations.DeleteModel(
            name='RainData',
        ),
        migrations.DeleteModel(
            name='RainDataFromFile',
        ),
        migrations.DeleteModel(
            name='ReplicatedDate',
        ),
        migrations.DeleteModel(
            name='ReplicatedDateDMY',
        ),
        migrations.DeleteModel(
            name='SurfaceLevelData',
        ),
        migrations.DeleteModel(
            name='SurfaceLevelDataFromFile',
        ),
        migrations.DeleteModel(
            name='TSSData',
        ),
        migrations.DeleteModel(
            name='WaterLevelData',
        ),
        migrations.DeleteModel(
            name='WaterLevelDataFromFile',
        ),
    ]
