# Generated by Django 5.1.5 on 2025-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0004_stationname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('highest_record', models.FloatField()),
                ('lowest_record', models.FloatField()),
                ('recorded_date', models.DateField()),
            ],
        ),
    ]
