# Generated by Django 5.1.5 on 2025-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0005_stationrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationrecord',
            old_name='highest_record',
            new_name='recorded_highest_wl',
        ),
        migrations.RenameField(
            model_name='stationrecord',
            old_name='lowest_record',
            new_name='recorded_lowest_wl',
        ),
        migrations.RemoveField(
            model_name='stationrecord',
            name='recorded_date',
        ),
        migrations.RemoveField(
            model_name='stationrecord',
            name='station_name',
        ),
        migrations.AddField(
            model_name='stationrecord',
            name='station_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
