# Generated by Django 5.1.5 on 2025-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0006_rename_highest_record_stationrecord_recorded_highest_wl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spikedata',
            name='modified_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
