# Generated by Django 5.1.5 on 2025-01-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0007_spikedata_modified_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spikedata',
            old_name='modified_value',
            new_name='modified_values',
        ),
    ]
