# Generated by Django 5.1.5 on 2025-01-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0008_rename_modified_value_spikedata_modified_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spikedata',
            old_name='modified_values',
            new_name='modified_value',
        ),
    ]
